version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chatroom
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7.0
    restart: unless-stopped
    ports:
      - "6379:6379"
  go-app:
    build: .
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: chatroom
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"

volumes:
  mysql_data: